name: all_bluetooth
description: "This plugin that allows to implement bluetooth features. Listen to bluetooth state, connecting to devices, sending data etc"
version: 0.1.0
homepage: https://github.com/rans-rans/all_bluetooth

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.rans_innovations.all_bluetooth
        pluginClass: AllBluetoothPlugin